Feature multiple repo
WalkingMachine/sara_commun pull request #44
Opened 2016-10-21 00:13 UTC by gortium

!!! Doit être mergé en même temps que la branch du même nom dans sara_robot !!!

Sinon.. je crois que c'est bon ^^

2016-10-21 00:19 UTC, gregoirefra requested changes
Est-ce que tu peux décrire les étapes à suivre une fois merge pour que nos environements soit a nouveau fonctionnel parce que j'assume que ceci va changer beaucoup de chose si quelqu'un fait juste pull les changements après. Je refuse aussi le merge juste pour l'instant pas qu'il y aille un merge accidentelle

2016-10-21 00:22 UTC, gortium commented
Ouais oublis ca, il reste du travail a faire pour bien tout démêler !

2016-10-21 00:55 UTC, gortium commented
Donc si tout va bien, normalement sur un desktop il n'y a rien a faire sauf pull les change de sara_commun.
Sur SARA, seulement pull les change de sara_commun et sara_robot. les deux devant être dans src.
Dans les deux cas je deleterais devel/ et build/ pour faire une catkin_make propre et assurer que ca marche.

2016-10-25 13:57 UTC, gortium commented
@gregoirefra Commence ici et suis les instruction pour multipleRepo.

2016-10-25 14:10 UTC, gregoirefra requested changes
A review from someone else like @maximest-pierre and/or @JeffCousineau is also required before merge since this is a major change.

2016-10-25 14:10 UTC, gregoirefra commented on wm_2dnav/config/base_local_planner_params.yaml
> +  escape_vel: 0.2
Are those change related to the new repo structure or have been introduced by mistake?

2016-10-25 14:10 UTC, gregoirefra commented on wm_2dnav/config/base_local_planner_params.yaml
> +  holonomic_robot: true
Are those change related to the new repo structure or have been introduced by mistake?

2016-10-25 14:10 UTC, gregoirefra commented on wm_2dnav/config/base_local_planner_params.yaml
> +  y_vels: [-0.4, -0.2, 0.2, 0.4]
Are those change related to the new repo structure or have been introduced by mistake?

2016-10-25 14:10 UTC, gregoirefra commented on wm_2dnav/config/base_local_planner_params.yaml
> +  sim_time: 0.5
Are those change related to the new repo structure or have been introduced by mistake?

2016-10-25 14:10 UTC, gregoirefra commented on wm_2dnav/config/base_local_planner_params.yaml
> +  vx_samples: 5 # default: 3
Are those change related to the new repo structure or have been introduced by mistake?

2016-10-25 14:10 UTC, gregoirefra commented on wm_2dnav/config/base_local_planner_params.yaml
> +  occdist_scale: 0.2
Are those change related to the new repo structure or have been introduced by mistake?

2016-10-25 14:10 UTC, gregoirefra commented on wm_2dnav/config/base_local_planner_params.yaml
> +  prune_plan: true
Are those change related to the new repo structure or have been introduced by mistake?

2016-10-25 14:10 UTC, gregoirefra commented on wm_2dnav/config/costmap_common_params.yaml
> +inflation_radius: 0.10
Are those change related to the new repo structure or have been introduced by mistake?

2016-10-25 14:14 UTC, gortium commented
Jai pull master.. Mais c'est change ont été introduit dans master sans passer par la branch dévelop.. Mauvaise pratique de bypass develop.. Ca donne ca.

2016-10-27 19:25 UTC, gregoirefra approved these changes

2016-10-28 00:53 UTC, merged